### ISSUE TITLE
Please add prefixes "pass-" and "fail-" to testfile names in branch alb001_alignment-in-spatial-structure

### ISSUE THREAD

**Issue by apinzenoehler** [buildingSMART/ifc-gherkin-rules#10]
The testfile directory for "branch alb001_alignment-in-spatial-structure" contains two files "File001.ifc" and "File002.ifc". It would be great, if the would be named according to their respective expected result. Looking into README.md this would be

"Pass-File001.ifc" and 
"Fail-File002.ifc"

BR Andreas

**Comment by evandroAlfieri** [comment]
Thanks for the feedback. I've pushed documentation on how to create rules and unit test files in the repository. For example, see the file naming convention part here: https://github.com/buildingSMART/ifc-gherkin-rules/blob/main/features/README.md#23-write-unit-test-files).

Assigning this to @Ghesselink, @JTurbakiewicz and @aothms to adjusting current examples
