### ISSUE TITLE
ALS010 - IfcShapeRepresentation with Type=Segment should have exactly 1 item

### ISSUE THREAD

**Issue by aothms** [buildingSMART/ifc-gherkin-rules#105]
From: https://github.com/IfcOpenShell/IfcOpenShell/pull/3945#issuecomment-1788133258

![afbeelding](https://github.com/buildingSMART/ifc-gherkin-rules/assets/1096535/6b2746a5-ce6c-46b7-9192-110f7fc57515)

The concept template language is not able to specify this.

**Comment by evandroAlfieri** [comment]
ALS010?

**Comment by civilx64** [comment]
Agree on ALS prefix.  Not sure about next available index.  Currently it appears that ALS008 would be next available but that would change after 006 and 007 are renamed to 001 and 002 respectively per review comments on #106.

**Comment by civilx64** [comment]
@evandroAlfieri please rename from `ALSXXX` to `ALS010` per discussion this week.

**Comment by civilx64** [comment]
ALS010 has been merged and will be present in the next update of the validation service.
