### ISSUE TITLE
Rules in ALB001_Alignment-in-spacial-structure.feature might be premature

### ISSUE THREAD

**Issue by apinzenoehler** [buildingSMART/ifc-gherkin-rules#12]
Gherkin-feature file "ALB001_Alignment-in-spacial-structure.feature" contains the following rule:

      Scenario Outline: Agreement on each IfcAlignment being contained in an IfcSite

          Given A file with Schema Identifier "<schema_identifier>"
          And An IfcAlignment
          Then Each IfcAlignment must be contained in IfcSite

There is an ongoing discussion in bSI implementer forum which might come to a different conclusion.

BR Andreas

**Comment by evandroAlfieri** [comment]
Good point, thanks Andreas. This rule was used as exercise to practice with Gherking and python implementation. We won't merge it before an agreement is reached. But I'll leave the branch open as this is still a good example of how to write rules for the Validation Service
