### ISSUE TITLE
Inconsistent capital "O" in the file name

### ISSUE THREAD

**Issue by evandroAlfieri** [buildingSMART/ifc-gherkin-rules#126]
https://github.com/buildingSMART/ifc-gherkin-rules/blob/f6d10cf03d0acc7a0a94383185402e642803e114/features/IFC001-only-official-ifc-versions-allowed.feature#L4

@Ghesselink can you change the file name to be consistent with the other feature files? Thanks

**Comment by Ghesselink** [comment]
Yes, can you approve?
https://github.com/buildingSMART/ifc-gherkin-rules/pulls
