### ISSUE TITLE
Nested by instead of nests

### ISSUE THREAD

**Issue by ciro-vendrame** [buildingSMART/ifc-gherkin-rules#16]
https://github.com/buildingSMART/ifc-gherkin-rules/blob/81b07c03b8c9726b4c0b580eb0efd63c1899ab2e/features/ALB002_Alignment-layout.feature#L48

Here (and in the 2 following scenarios) probably we need to say : 
And the element is nested by...
Instead of:
And the element nests...

**Comment by aothms** [comment]
I made the same comment https://github.com/buildingSMART/ifc-gherkin-rules/pull/6#discussion_r1039436938

**Comment by Ghesselink** [comment]
`>>> file.by_type('IfcAlignmentSegment')[0].Nests[0].RelatingObject
#28=IfcAlignmentHorizontal('2jGhr68$16zfnzcuHgL0Yf',#1,'AH1',$,$,$,$)
>>> file.by_type('IfcAlignmentSegment')[0].IsNestedBy
()`
That means that Gherkin and IFC should be reversed? https://github.com/buildingSMART/ifc-gherkin-rules/pull/6#discussion_r1039436938 Was commented in a given statement which was already reversed relative to IFC. 
Both comments cannot be true at the same time ..

**Comment by aothms** [comment]
@Ghesselink is correct I think. It's confusing in IFC, but `nests` means "being part of", `is nested by` means "having parts". In this particular case the `IfcAlignmentSegment` is being part of `IfcAlignmentHorizontal` so this seems correct. @ciro-vendrame can you have another look?

**Comment by ciro-vendrame** [comment]
Hi Thomas, sorry for the late reply.
Yes I agree, thanks to you and @Ghesselink.
I close this issue.
