### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ciro-vendrame** [buildingSMART/ifc-gherkin-rules#17]
https://github.com/buildingSMART/ifc-gherkin-rules/blob/81b07c03b8c9726b4c0b580eb0efd63c1899ab2e/features/ALB002_Alignment-layout.feature#L52-L59

In these Scenarios the word "horizontal" in the agreement statement should be replaced by "vertical" and "cant" respectively

**Comment by Ghesselink** [comment]
Fixed in https://github.com/buildingSMART/ifc-gherkin-rules/pull/6/commits/66f3c3c4c014422b1816bfd077ed089798ed1dc2
