### ISSUE TITLE
A question on entities order

### ISSUE THREAD

**Issue by ciro-vendrame** [buildingSMART/ifc-gherkin-rules#18]
https://github.com/buildingSMART/ifc-gherkin-rules/blob/81b07c03b8c9726b4c0b580eb0efd63c1899ab2e/features/ALB002_Alignment-layout.feature#L27

Is there a specific order the SW vendors expect these entities?
I also suppose there is already an agreement in place for which IfcReferent shall be nested in IfcAlignment and not in IfcAlignment Horizontal, am I right?

**Comment by aothms** [comment]
Currently this statement is only about the allowed types irrespective about order. It is implemented as a (unordered) set comparison https://github.com/buildingSMART/ifc-gherkin-rules/pull/6/files#diff-cf027576a6812e3403bd3d9579d83abfaa74a41607a4f3c986398ef8492a5d3dR270

I'll assign this to @evandroAlfieri if the unordered nature of this constraint needs to be made explicit in gherkin and about the question on referent.

**Comment by evandroAlfieri** [comment]
Good point Ciro. For this and other reasons, I'd follow the suggestion of @pjanck here: https://github.com/buildingSMART/ifc-gherkin-rules/pull/6#discussion_r1036142227
**Let's move that sentence in a dedicated ALB rule (e.g., ALB003_Allowed entities nested in Alignment).**

I'll discuss this specific topic with vendors in the IF. I guess a comprehensive rule should say:
- what are the allowed entities that can be nested in alignment (the full list is the one in the current sentence)
- what order shall they have, when present

If I remember correctly, it has been said once that:
- alignment layouts must be in one RelNests relationship, with order H-V-C
- referents shall be in another RelNests than the one of the alignment layouts
- other alignment shall be in another RelNests than the one of alignment layouts, and referents

I'll confirm with SV and come back to you. Meanwhile, @Ghesselink can we take this step out of the ALB002 rule?

**Comment by Ghesselink** [comment]
The scenario is removed in https://github.com/buildingSMART/ifc-gherkin-rules/pull/6/commits/e5efda347d083e88c593b99a4324a8c4a28735ec 
I've saved the python code, gherkin feature and (code to generate-) testfiles locally. The assigned person(s) for this new created rule (if not myself) can contact me if they'd like to have it.

**Comment by Ghesselink** [comment]
Moved to https://github.com/buildingSMART/ifc-gherkin-rules/pull/26
