### ISSUE TITLE
PSE001 - Triggered with a correct file

### ISSUE THREAD

**Issue by michelangelo-acca** [buildingSMART/ifc-gherkin-rules#198]
Can you check why the PSE001 is triggered with the following file? It seems ok to me...

**Comment by michelangelo-acca** [comment]
[PSE001.zip](https://github.com/user-attachments/files/15515611/PSE001.zip)

**Comment by michelangelo-acca** [comment]
Cannot add Assignees...pinging @aothms @evandroAlfieri

**Comment by evandroAlfieri** [comment]
Strange indeed.
![image](https://github.com/buildingSMART/ifc-gherkin-rules/assets/62438551/8219e4a6-bbfb-4743-b72a-f49f30daad27)
@aothms can you have a look?

**Comment by aothms** [comment]
Thanks for reporting this @michelangelo-acca 

I don't know if this makes it better or worse, but the issue stems from the IFC4 PSD XML data, which contains a space before IfcWindow in this particular property set definition.

![afbeelding](https://github.com/buildingSMART/ifc-gherkin-rules/assets/1096535/fd021e9c-f867-4695-9ccb-97db8b36ee5b)

https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/psd/Pset_DoorWindowGlazingType.xml

We'll review our imported data, deploy a fix for this quickly (tentatively end of week) and report back here.

**Comment by evandroAlfieri** [comment]
Fixed by https://github.com/buildingSMART/ifc-gherkin-rules/pull/202
Will be included in the 0.6.3 relase
