### ISSUE TITLE
say hello ... 

### ISSUE THREAD

**Issue by berndhahnebach** [buildingSMART/ifc-gherkin-rules#2]
Hi Thomas, Hi Leo,

very good idea to collect gherkin rules.

I had a short conversation with Leo today ... Just to give you guys an update. In the company I work for I have set up an automatic testing tool based on BIMTester. Every ifc which was exported from CAD and which is intended to be  used will be tested by BIMTester. For this I have extended the tests a lot and did some changes on the base system in the regard of my needs. I have not merged them back to official ifcopenshell just limited time range last few month because of a little boy who was born in summer 2021. There will be some work to do in this regard. All changes in one commit can be seen here: https://github.com/berndhahnebach/IfcOpenShell/commit/4f9310f24b6a9  There is some work needed to sort this out. This work hast started already. The interesting part of the story can be seen here ... https://github.com/berndhahnebach/IfcOpenShell/tree/4f9310f24b6a95a0ce927ad01bf55a743b59659a/src/ifcbimtester/bimtester/features

How about Dion? Is he involved too? BIMTester was his baby even if he did not really continued development anymore at some point.

How do we decide which step changes go to official IfcOpenShell and which go here?

Who maintains this repo?

How about licence? There is no ATM?

cheers bernd

**Comment by aothms** [comment]
Hi Bernd, thanks for reaching out. Congrats on the birth of your son!

First of all I think the intention of the rules is a bit different. Dion and you (I assume) have been mostly working at things an end-user would want to specify. This repository is more about things related to the validity of IFC models on a more technical level (think implementer agreements) and requirements in the specification that are difficult or impossible to formalize into the schema (think geometry informal propositions).

So I think the reason @berlotti reached out to you is (a) general thoughts, but maybe also (b) seeing whether you are interested in contributing to this. I see it a bit more disjoint from the existing rules currently being developed on bimtester.

@Moult has obviously been in the loop on all of this. In my view, it seems that with the massive push IDS has seen lately https://github.com/Moult/tmp-ids-spec/blob/main/README.md quite some things can move out of bimtester. What remains are probably really specific and advanced rules that are going to be part of the new ifctester?

For us it was important to really stay on unaltered tools. So what you see in this repository is really just vanilla gherkin/behave.

bSI will maintain the repository and the license will probably be a somewhat in line with the IFC schema itself?

**Comment by berndhahnebach** [comment]
Hi Thomas,

thanks for the information and the link to the ids spec. In conjunction with the slides from a talk Leon gave I got the point of the ifc-gherkin-rules.

cheers Bernd
