### ISSUE TITLE
ALA003 - Maybe wrong with Cant

### ISSUE THREAD

**Issue by michelangelo-acca** [buildingSMART/ifc-gherkin-rules#213]
In an attempt to update the file from https://github.com/buildingSMART/IFC4.x-IF/issues/151 to pass the latest bSI Validation Checks, we noticed it fails on the ALA003 rule claiming that since the Semantic part of the Cant is using LinearTransition, the Geometry should use Lines and not Clothoids as per in the file.

This may be incorrect, leaving the floor to @peterrdf for the technicalities and pinging @evandroAlfieri and @aothms as it is not possible to set assignees.

Also, attaching the current version of the file for testing.

[ACCA_sleepers-linear-placement-cant-implicit.zip](https://github.com/user-attachments/files/15816340/ACCA_sleepers-linear-placement-cant-implicit.zip)

**Comment by civilx64** [comment]
The validation service is correct. See discussion at [IFC4.x-IF#145](https://github.com/buildingSMART/IFC4.x-IF/issues/145)

**Comment by peterrdf** [comment]
I am quite sure this is a mistake in the validatiohn service, any possibility for a call?

**Comment by RickBrice** [comment]
@civilx64 @evandroAlfieri @michelangelo-acca 

I tend to agree with @peterrdf on this one. See https://github.com/buildingSMART/IFC4.x-IF/issues/145#issuecomment-2168385958

**Comment by civilx64** [comment]
After some helpful discussion in [IFC4.x-IF/#145](https://github.com/buildingSMART/IFC4.x-IF/issues/145) I am coming around to the majority view here and anticipate a revision to ALA003 in the Validation Service.
