### ISSUE TITLE
SPS007 - Maybe fails with a correct file

### ISSUE THREAD

**Issue by michelangelo-acca** [buildingSMART/ifc-gherkin-rules#214]
Hi again,

why does the following file fail the SPS007 rule? It is a Wall with a Window...I always tought that the Wall should have the RelContainedInSpatialStructure and not the Window, but it seems the opposite is true...

[aaa.zip](https://github.com/user-attachments/files/15821065/aaa.zip)

**Comment by evandroAlfieri** [comment]
Thanks @michelangelo-acca, it's a known bug. The relationship was implemented the other way around.
It's already fixed by https://github.com/buildingSMART/ifc-gherkin-rules/pull/211 we are packaging this with other fixes and we'll soon deploy a new version
