### ISSUE TITLE
Resolving comments

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/ifc-gherkin-rules#24]
@aothms I can't resolve my own comments on a PR - is there a setting I need to make?

**Comment by evandroAlfieri** [comment]
For now, I would suggest the good practice where **the person opening the PR is responsible for resolving all conversations - before the PR is approved**.
cc: @aothms @Ghesselink @JTurbakiewicz @johltn 

If the suggestion in a comment is out of a pull request's scope, or if the reviewer is not happy with the resolution, or if the comments triggered a bigger discussion, in all these cases I suggest that anyone can open a new issue that tracks the feedback and links back to the original comment. See "[Opening an issue from a comment](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-comment)"

**Comment by pjanck** [comment]
Right, so be it.
