### ISSUE TITLE
ALB012 IfcAlignmentVerticalSegment.RadiusOfCurvature

### ISSUE THREAD

**Issue by RickBrice** [buildingSMART/ifc-gherkin-rules#241]
Not sure if you are intending to check IfcAlignmentVerticalSegment.RadiusOfCurvature since it is an optional parameter. I found a case where the VS doesn't recognize the RadiusOfCurve is not consistent with the curve parameters.

`#119=IFCALIGNMENTVERTICALSEGMENT($,$,365.76,487.68,36.8808,0.0175,-0.01,100.0,.PARABOLICARC.);`

Radius of curvature should be 487.68/(-0.01 - 0.0175) = -17733.81818.

I changed the value to 100.0 to see if the VS would detected it.

[FHWA_Bridge_Geometry_Alignment_Bridge_1.ifc.txt](https://github.com/user-attachments/files/16289800/FHWA_Bridge_Geometry_Alignment_Bridge_1.ifc.txt)

**Comment by evandroAlfieri** [comment]
Good suggestion for a "sanity check". To make it explicit:
RadiusOfCurvature = HorizontalLength / (EndGradient-StartGradient)

**Comment by civilx64** [comment]
@RickBrice since `HorizontalLength` is of type `IfcLengthMeasure` and could therefore potentially be negative, do we need to take the absolute value in the numerator?  It would appear so based on internal testing of rule ALB012 - but I wanted to confirm.

**Comment by RickBrice** [comment]
@civilx64 I would think that the absolute value of HorizontalLength would be more appropriate. The sign of the start and end gradients will provide the correct sign for the RadiusOfCurvature.

For sag VC, Start Gradient (SG)< 0, End Gradient (EG) > 0
ROC = ABS(HorizLength)/(EG - SG) > 0 = CCW per the spec

**Comment by civilx64** [comment]
Yes, abs(HorizontalLength) is what I was thinking as the numerator or first term in the equation. 

Thanks for confirming!

**Comment by RickBrice** [comment]
My bad - you did say numerator, my brain was thinking denominator.

**Comment by civilx64** [comment]
released in Validation Service [version 0.6.8](https://forums.buildingsmart.org/t/validation-service-updates/4992/14?u=evandro).
