### ISSUE TITLE
GEM052 IFC4 Scenario

### ISSUE THREAD

**Issue by isma3lMB** [buildingSMART/ifc-gherkin-rules#268]
This ends up checking if the _ContextType_  is within the list of valid _RepresentationType_ which is always a fail

https://github.com/buildingSMART/ifc-gherkin-rules/blob/f7dcaac762beb0c613d46f29fe94ca8aa778f9dd/features/GEM052_Correct-geometric-subcontexts.feature#L24-L29

**Comment by evandroAlfieri** [comment]
Thanks both for reporting it. It's a known issue, already fixed and will be included in next release of the service

**Comment by evandroAlfieri** [comment]
This issue has been fixed by 0.6.6 release https://github.com/buildingSMART/ifc-gherkin-rules/commit/c5808bfa00bbfc3cfed53ffc8d92cd3e0ce34491
