### ISSUE TITLE
General dude about this repo

### ISSUE THREAD

**Issue by IbimDesarrollo** [buildingSMART/ifc-gherkin-rules#49]
Can someone explain me was the difference between gherkin rules and IDS standard? I see that both can check ifc models, but i dont know why development it is not focus in one system.
Thanks in advance

**Comment by evandroAlfieri** [comment]
The **bSI Validation Service** (which uses Gherkin rules for some of its checks) validate an IFC files against syntax, schema, and other constraints of the IFC standard (schema + specification). It tells you if your file is a valid IFC file.

**IDS** can be use to demand (and check) information that are specific for a use-case, a project, an organisation, etc. You can use it to check if an IFC file contains the information you needed for a specific use.

Corollary: they are not "competing systems". they complement each others. That is why there was (is) effort in both directions, and not only one.
