### ISSUE TITLE
Remove "IFC4x1" from the Given

### ISSUE THREAD

**Issue by evandroAlfieri** [buildingSMART/ifc-gherkin-rules#66]
https://github.com/buildingSMART/ifc-gherkin-rules/blob/47b6a14abb41da91b97d5ca65dc3c1f1ab243429/features/GRF001_Identical-coordinate-operations.feature#L8

**Comment by Ghesselink** [comment]
https://github.com/buildingSMART/ifc-gherkin-rules/pull/70

**Comment by JTurbakiewicz** [comment]
@evandroAlfieri  @Ghesselink,

@Ghesselink has removed IFC4x1 from the rule with https://github.com/buildingSMART/ifc-gherkin-rules/commit/1b2f0ae45e9fcd1ab98f0e53d12217ad903bbf7b

I've checked and IFC4x1 is not present anywhere else in repo. I'm closing the issue.
