### ISSUE TITLE
IFCMAPCONVERSION has 8 arguments instead of 10

### ISSUE THREAD

**Issue by apinzenoehler** [buildingSMART/ifc-gherkin-rules#7]
File https://github.com/buildingSMART/ifc-gherkin-rules/blob/alb002_alignment-layout/test/files/alb002/pass-alb002-alignment-layout.ifc has problem with IFCMAPCONVERSION

#904 = IFCMAPCONVERSION(#13, #905, 0., 0., 0., 1., 0., 1.);
instead of
#904 = IFCMAPCONVERSION(#13, #905, 0., 0., 0., 1., 0., 1., $, $);

BR Andreas

**Comment by Ghesselink** [comment]
Thanks, It's updated in https://github.com/buildingSMART/ifc-gherkin-rules/commit/a2cb53eab60945381cdf768d052c4e76594a480e 
I've checked, but it is not in the fail files, which is weird (for me at least) since these files are generated with the mentioned file as a base.
