### ISSUE TITLE
Proposal for addtional column in README.md for testfile folders

### ISSUE THREAD

**Issue by apinzenoehler** [buildingSMART/ifc-gherkin-rules#8]
Example: https://github.com/buildingSMART/ifc-gherkin-rules/tree/alb002_alignment-layout/test/files/alb002

It would be nice if it is stated what category of failure should be detected for the testfile.

Proposal: new column "Category" between "Expected result" and "Error". 

Possible values:
* Syntax
* Schema
* bSDD
* IA (Implementer Agreement)
* IP (Informal proposition)

BR Andreas

**Comment by evandroAlfieri** [comment]
Thanks for the feedback. I'm closing this as gherkin rules (and related unit test files) are not used to check syntax, schema, nor bSDD
