### ISSUE TITLE
"fail-file" does not fail in https://validate.buildingsmart.org

### ISSUE THREAD

**Issue by apinzenoehler** [buildingSMART/ifc-gherkin-rules#9]
Testfile "fail-alb002-scenario04-alignment_segments.ifc" does not raise an error in https://validate.buildingsmart.org.

Genuine misbehaviour of the validation service?
Tested to early?

BR Andreas

**Comment by aothms** [comment]
You need to check in the sandbox where the updated propositions are loaded.

https://validate.buildingsmart.org/sandbox/a33767f28032eb37600de5d4d0bb6834773bd60e

![afbeelding](https://user-images.githubusercontent.com/1096535/204308983-42387d72-bd36-4d09-9719-863426f33b36.png)

**Comment by Ghesselink** [comment]
I think that's because this pull request is not yet merged into the main repository and in the production environment.

**Comment by apinzenoehler** [comment]
> You need to check in the sandbox where the updated propositions are loaded.
> 
> https://validate.buildingsmart.org/sandbox/a33767f28032eb37600de5d4d0bb6834773bd60e
> 
> ![afbeelding](https://user-images.githubusercontent.com/1096535/204308983-42387d72-bd36-4d09-9719-863426f33b36.png)

After login with my bSI-account into the validation service this link yields:

    Not Found
    The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again

Missing authorization?

**Comment by aothms** [comment]
No with additional commits added to the pull request the sandbox is now moved to:

https://validate.buildingsmart.org/sandbox/e31cf2000e3b4f1fed553d4728b9217b142c6b7a

**Comment by apinzenoehler** [comment]
Thank you very much.

Test now yields a "fail" as expected.

    [ALB002 - Alignment Layout/Agreement on structure of alignment segments.v3](https://github.com/buildingSMART/ifc-gherkin-rules/blob/a33767f/features/ALB002_Alignment-layout.feature)
    • Each IfcAlignmentHorizontal nests a list of IfcAlignmentSegment, each of which has DesignParameters typed as IfcAlignmentHorizontalSegment
    The instance #28=IfcAlignmentHorizonta...,$,$,$) is nesting [#906=IfcWall('19KKGlRZ0H...$,$,$)]
